version: "3.8"

services:
  app:
    build:
      context: fpm
    container_name: larasendfile-app
    working_dir: /application
    volumes:
      - ../repo:/application:cached

  web:
    image: nginx:1-alpine
    container_name: larasendfile-web
    working_dir: /application
    volumes:
      - ../repo:/application:cached
      - ../repo/public/storage:/application/storage/app/public:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80